### ISSUE TITLE
Running on Arm64 ?

### ISSUE THREAD

**Issue by techc0de** [theniwo/clonezilla#2]
Hi,

I'm been looking for a docker image for Clonezilla a long time, and thanks for created this image.
I got an error when the container is running on RPI4.

`
standard_init_linux.go:228: exec user process caused: exec format error`

Can you advise how to fix this ?

Thanks

**Comment by theniwo** [comment]
Hi unfortunately this image is build to run on x86/AMD64 architecture only.

**Comment by techc0de** [comment]
is there a way I can convert it to ARM64 ?

**Comment by theniwo** [comment]
You can try another image that is suitable for arm like https://hub.docker.com/r/ltdgbchedu/clonezilla
